channels:
- conda-forge
dependencies:
- python=3.11.11
- pip<=25.0
- pip:
  - mlflow==2.18.0
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - packaging==24.2
  - pandas==2.2.3
  - psutil==7.0.0
  - pyyaml==6.0.2
  - scikit-learn==1.6.1
  - scipy==1.15.2
name: mlflow-env
